LOAD DATA LOCAL INFILE "Item.csv"          INTO TABLE Item
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE "User.csv"          INTO TABLE User
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE "ItemCategory.csv"  INTO TABLE ItemCategory
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE "Bid.csv"           INTO TABLE Bid
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\n';
